name: Release vscode extension

on: 
  release:
    types: [published]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Extract version from tag
      id: extract_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
      
    - name: Update package version
      working-directory: ./fosslight-scanner
      run: npm version ${{ env.VERSION }} --no-git-tag-version
      
    - name: Install vsce
      run: npm install -g vsce

    - name: Publish VS Code Extension
      env:
        VSCE_PAT: ${{ secrets.VSCE_TOKEN }}
      run: |
        vsce package
        vsce publish
